# Generated by Django 5.0 on 2023-12-26 06:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=12, region=None),
            preserve_default=False,
        ),
    ]
