# Generated by Django 5.0 on 2023-12-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_customer_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
